[2022-07-26 11:51:54,107] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-25T00:00:00+00:00 [queued]>
[2022-07-26 11:51:54,132] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-25T00:00:00+00:00 [queued]>
[2022-07-26 11:51:54,139] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:51:54,141] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2022-07-26 11:51:54,142] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:51:54,181] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-25 00:00:00+00:00
[2022-07-26 11:51:54,192] {standard_task_runner.py:52} INFO - Started process 1461 to run task
[2022-07-26 11:51:54,224] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'scheduled__2022-07-25T00:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp5we5q3e6', '--error-file', '/tmp/tmpgpbfu4bw']
[2022-07-26 11:51:54,229] {standard_task_runner.py:80} INFO - Job 101: Subtask task1
[2022-07-26 11:51:54,474] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 scheduled__2022-07-25T00:00:00+00:00 [running]> on host 24820bb59fd1
[2022-07-26 11:51:54,706] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-25T00:00:00+00:00
[2022-07-26 11:51:54,709] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 11:51:54,711] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 11:51:54,737] {subprocess.py:85} INFO - Output:
[2022-07-26 11:51:54,756] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 11:51:54,758] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 11:51:54,789] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 11:51:54,798] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=task1, execution_date=20220725T000000, start_date=20220726T115154, end_date=20220726T115154
[2022-07-26 11:51:54,838] {standard_task_runner.py:97} ERROR - Failed to execute job 101 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 1461)
[2022-07-26 11:51:54,880] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 11:51:55,005] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
