[2022-07-26 11:53:55,902] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-25T00:00:00+00:00 [queued]>
[2022-07-26 11:53:55,939] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-25T00:00:00+00:00 [queued]>
[2022-07-26 11:53:55,942] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:53:55,943] {taskinstance.py:1377} INFO - Starting attempt 4 of 6
[2022-07-26 11:53:55,943] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:53:55,986] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-25 00:00:00+00:00
[2022-07-26 11:53:56,003] {standard_task_runner.py:52} INFO - Started process 1583 to run task
[2022-07-26 11:53:56,026] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'scheduled__2022-07-25T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmppbpi3a0d', '--error-file', '/tmp/tmp9t4y27fh']
[2022-07-26 11:53:56,032] {standard_task_runner.py:80} INFO - Job 106: Subtask task1
[2022-07-26 11:53:56,236] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 scheduled__2022-07-25T00:00:00+00:00 [running]> on host 24820bb59fd1
[2022-07-26 11:53:56,446] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-25T00:00:00+00:00
[2022-07-26 11:53:56,449] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 11:53:56,455] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 11:53:56,502] {subprocess.py:85} INFO - Output:
[2022-07-26 11:53:56,506] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 11:53:56,507] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 11:53:56,568] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 11:53:56,591] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=task1, execution_date=20220725T000000, start_date=20220726T115355, end_date=20220726T115356
[2022-07-26 11:53:56,623] {standard_task_runner.py:97} ERROR - Failed to execute job 106 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 1583)
[2022-07-26 11:53:56,648] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 11:53:56,808] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
