[2022-07-26 11:47:48,195] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T11:47:37.017476+00:00 [queued]>
[2022-07-26 11:47:48,495] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T11:47:37.017476+00:00 [queued]>
[2022-07-26 11:47:48,505] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:47:48,508] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-07-26 11:47:48,510] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:47:48,723] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-26 11:47:37.017476+00:00
[2022-07-26 11:47:48,800] {standard_task_runner.py:52} INFO - Started process 1226 to run task
[2022-07-26 11:47:48,869] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'manual__2022-07-26T11:47:37.017476+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpwa0xstkc', '--error-file', '/tmp/tmpnuh81lnq']
[2022-07-26 11:47:48,882] {standard_task_runner.py:80} INFO - Job 90: Subtask task1
[2022-07-26 11:47:49,766] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 manual__2022-07-26T11:47:37.017476+00:00 [running]> on host 24820bb59fd1
[2022-07-26 11:47:50,710] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T11:47:37.017476+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T11:47:37.017476+00:00
[2022-07-26 11:47:50,713] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 11:47:50,715] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 11:47:50,802] {subprocess.py:85} INFO - Output:
[2022-07-26 11:47:50,908] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 11:47:50,910] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 11:47:50,988] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 11:47:51,003] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=task1, execution_date=20220726T114737, start_date=20220726T114748, end_date=20220726T114751
[2022-07-26 11:47:51,081] {standard_task_runner.py:97} ERROR - Failed to execute job 90 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 1226)
[2022-07-26 11:47:51,166] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 11:47:51,534] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
