[2022-07-26 11:51:54,099] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T11:47:37.017476+00:00 [queued]>
[2022-07-26 11:51:54,122] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T11:47:37.017476+00:00 [queued]>
[2022-07-26 11:51:54,123] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:51:54,125] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2022-07-26 11:51:54,126] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:51:54,163] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-26 11:47:37.017476+00:00
[2022-07-26 11:51:54,172] {standard_task_runner.py:52} INFO - Started process 1459 to run task
[2022-07-26 11:51:54,183] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'manual__2022-07-26T11:47:37.017476+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpajoyv8y5', '--error-file', '/tmp/tmpw3eo0dc4']
[2022-07-26 11:51:54,186] {standard_task_runner.py:80} INFO - Job 102: Subtask task1
[2022-07-26 11:51:54,420] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 manual__2022-07-26T11:47:37.017476+00:00 [running]> on host 24820bb59fd1
[2022-07-26 11:51:54,666] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T11:47:37.017476+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T11:47:37.017476+00:00
[2022-07-26 11:51:54,687] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 11:51:54,698] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 11:51:54,759] {subprocess.py:85} INFO - Output:
[2022-07-26 11:51:54,762] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 11:51:54,763] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 11:51:54,804] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 11:51:54,813] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=task1, execution_date=20220726T114737, start_date=20220726T115154, end_date=20220726T115154
[2022-07-26 11:51:54,848] {standard_task_runner.py:97} ERROR - Failed to execute job 102 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 1459)
[2022-07-26 11:51:54,889] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 11:51:54,974] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
