[2022-07-26 11:51:54,103] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2022-07-26 11:51:54,126] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2022-07-26 11:51:54,127] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:51:54,129] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2022-07-26 11:51:54,130] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:51:54,163] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-22 00:00:00+00:00
[2022-07-26 11:51:54,172] {standard_task_runner.py:52} INFO - Started process 1460 to run task
[2022-07-26 11:51:54,185] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'scheduled__2022-07-22T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp86ks9irz', '--error-file', '/tmp/tmp_7hlnbqn']
[2022-07-26 11:51:54,189] {standard_task_runner.py:80} INFO - Job 100: Subtask task1
[2022-07-26 11:51:54,352] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 scheduled__2022-07-22T00:00:00+00:00 [running]> on host 24820bb59fd1
[2022-07-26 11:51:54,511] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-22T00:00:00+00:00
[2022-07-26 11:51:54,517] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 11:51:54,520] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 11:51:54,547] {subprocess.py:85} INFO - Output:
[2022-07-26 11:51:54,560] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 11:51:54,562] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 11:51:54,613] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 11:51:54,625] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=task1, execution_date=20220722T000000, start_date=20220726T115154, end_date=20220726T115154
[2022-07-26 11:51:54,691] {standard_task_runner.py:97} ERROR - Failed to execute job 100 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 1460)
[2022-07-26 11:51:54,735] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 11:51:54,843] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
