[2022-07-26 11:53:55,754] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2022-07-26 11:53:55,826] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-22T00:00:00+00:00 [queued]>
[2022-07-26 11:53:55,847] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:53:55,858] {taskinstance.py:1377} INFO - Starting attempt 4 of 6
[2022-07-26 11:53:55,860] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:53:55,936] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-22 00:00:00+00:00
[2022-07-26 11:53:55,949] {standard_task_runner.py:52} INFO - Started process 1582 to run task
[2022-07-26 11:53:55,970] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'scheduled__2022-07-22T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp8edpw801', '--error-file', '/tmp/tmp6e13q0dj']
[2022-07-26 11:53:55,976] {standard_task_runner.py:80} INFO - Job 104: Subtask task1
[2022-07-26 11:53:56,151] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 scheduled__2022-07-22T00:00:00+00:00 [running]> on host 24820bb59fd1
[2022-07-26 11:53:56,323] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-22T00:00:00+00:00
[2022-07-26 11:53:56,333] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 11:53:56,336] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 11:53:56,353] {subprocess.py:85} INFO - Output:
[2022-07-26 11:53:56,360] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 11:53:56,363] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 11:53:56,491] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 11:53:56,508] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=task1, execution_date=20220722T000000, start_date=20220726T115355, end_date=20220726T115356
[2022-07-26 11:53:56,566] {standard_task_runner.py:97} ERROR - Failed to execute job 104 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 1582)
[2022-07-26 11:53:56,628] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 11:53:56,823] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
