[2022-07-26 12:58:36,207] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T12:48:25.568719+00:00 [queued]>
[2022-07-26 12:58:36,222] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T12:48:25.568719+00:00 [queued]>
[2022-07-26 12:58:36,223] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 12:58:36,224] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2022-07-26 12:58:36,224] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 12:58:36,241] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-26 12:48:25.568719+00:00
[2022-07-26 12:58:36,249] {standard_task_runner.py:52} INFO - Started process 5298 to run task
[2022-07-26 12:58:36,256] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'manual__2022-07-26T12:48:25.568719+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmplj_7sv6t', '--error-file', '/tmp/tmppg_lwu1l']
[2022-07-26 12:58:36,259] {standard_task_runner.py:80} INFO - Job 126: Subtask task1
[2022-07-26 12:58:36,351] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 manual__2022-07-26T12:48:25.568719+00:00 [running]> on host 24820bb59fd1
[2022-07-26 12:58:36,436] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T12:48:25.568719+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T12:48:25.568719+00:00
[2022-07-26 12:58:36,438] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 12:58:36,439] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 12:58:36,452] {subprocess.py:85} INFO - Output:
[2022-07-26 12:58:36,454] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 12:58:36,455] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 12:58:36,473] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 12:58:36,478] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=our_first_dag, task_id=task1, execution_date=20220726T124825, start_date=20220726T125836, end_date=20220726T125836
[2022-07-26 12:58:36,492] {standard_task_runner.py:97} ERROR - Failed to execute job 126 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 5298)
[2022-07-26 12:58:36,510] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 12:58:36,560] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
