[2022-07-26 11:57:59,584] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-24T00:00:00+00:00 [queued]>
[2022-07-26 11:57:59,617] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 scheduled__2022-07-24T00:00:00+00:00 [queued]>
[2022-07-26 11:57:59,618] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:57:59,619] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2022-07-26 11:57:59,621] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 11:57:59,651] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-24 00:00:00+00:00
[2022-07-26 11:57:59,674] {standard_task_runner.py:52} INFO - Started process 1843 to run task
[2022-07-26 11:57:59,687] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'scheduled__2022-07-24T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpsrn8ogff', '--error-file', '/tmp/tmp80lu5sp6']
[2022-07-26 11:57:59,698] {standard_task_runner.py:80} INFO - Job 113: Subtask task1
[2022-07-26 11:57:59,931] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 scheduled__2022-07-24T00:00:00+00:00 [running]> on host 24820bb59fd1
[2022-07-26 11:58:00,272] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-24T00:00:00+00:00
[2022-07-26 11:58:00,280] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 11:58:00,287] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 11:58:00,327] {subprocess.py:85} INFO - Output:
[2022-07-26 11:58:00,331] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 11:58:00,334] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 11:58:00,373] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 11:58:00,386] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=our_first_dag, task_id=task1, execution_date=20220724T000000, start_date=20220726T115759, end_date=20220726T115800
[2022-07-26 11:58:00,435] {standard_task_runner.py:97} ERROR - Failed to execute job 113 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 1843)
[2022-07-26 11:58:00,483] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 11:58:00,624] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
