[2022-07-26 13:07:56,068] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T13:07:54.085594+00:00 [queued]>
[2022-07-26 13:07:56,093] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T13:07:54.085594+00:00 [queued]>
[2022-07-26 13:07:56,094] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 13:07:56,095] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-07-26 13:07:56,096] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 13:07:56,121] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-26 13:07:54.085594+00:00
[2022-07-26 13:07:56,130] {standard_task_runner.py:52} INFO - Started process 5837 to run task
[2022-07-26 13:07:56,148] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'manual__2022-07-26T13:07:54.085594+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpc892m0g4', '--error-file', '/tmp/tmp2ij3uhz2']
[2022-07-26 13:07:56,154] {standard_task_runner.py:80} INFO - Job 127: Subtask task1
[2022-07-26 13:07:56,300] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 manual__2022-07-26T13:07:54.085594+00:00 [running]> on host 24820bb59fd1
[2022-07-26 13:07:56,640] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T13:07:54.085594+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T13:07:54.085594+00:00
[2022-07-26 13:07:56,644] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 13:07:56,647] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 13:07:56,709] {subprocess.py:85} INFO - Output:
[2022-07-26 13:07:56,754] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 13:07:56,758] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 13:07:56,802] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 13:07:56,825] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=task1, execution_date=20220726T130754, start_date=20220726T130756, end_date=20220726T130756
[2022-07-26 13:07:56,852] {standard_task_runner.py:97} ERROR - Failed to execute job 127 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 5837)
[2022-07-26 13:07:56,931] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 13:07:57,009] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
