[2022-07-26 13:08:59,652] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T13:08:58.356560+00:00 [queued]>
[2022-07-26 13:08:59,678] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T13:08:58.356560+00:00 [queued]>
[2022-07-26 13:08:59,679] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 13:08:59,682] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-07-26 13:08:59,682] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 13:08:59,704] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-26 13:08:58.356560+00:00
[2022-07-26 13:08:59,716] {standard_task_runner.py:52} INFO - Started process 5909 to run task
[2022-07-26 13:08:59,723] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'manual__2022-07-26T13:08:58.356560+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpbza1blko', '--error-file', '/tmp/tmpxk_i2r_1']
[2022-07-26 13:08:59,726] {standard_task_runner.py:80} INFO - Job 130: Subtask task1
[2022-07-26 13:08:59,838] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 manual__2022-07-26T13:08:58.356560+00:00 [running]> on host 24820bb59fd1
[2022-07-26 13:08:59,939] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T13:08:58.356560+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T13:08:58.356560+00:00
[2022-07-26 13:08:59,943] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 13:08:59,946] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'helloword , first task']
[2022-07-26 13:08:59,966] {subprocess.py:85} INFO - Output:
[2022-07-26 13:08:59,979] {subprocess.py:92} INFO - bash: line 1: helloword: command not found
[2022-07-26 13:08:59,980] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 13:08:59,998] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 13:09:00,003] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=task1, execution_date=20220726T130858, start_date=20220726T130859, end_date=20220726T130900
[2022-07-26 13:09:00,020] {standard_task_runner.py:97} ERROR - Failed to execute job 130 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 5909)
[2022-07-26 13:09:00,071] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 13:09:00,127] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
