[2022-07-26 12:39:34,912] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T12:39:30.437728+00:00 [queued]>
[2022-07-26 12:39:35,721] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: our_first_dag.task1 manual__2022-07-26T12:39:30.437728+00:00 [queued]>
[2022-07-26 12:39:35,745] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 12:39:35,781] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-07-26 12:39:35,825] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 12:39:36,466] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): task1> on 2022-07-26 12:39:30.437728+00:00
[2022-07-26 12:39:36,974] {standard_task_runner.py:52} INFO - Started process 4179 to run task
[2022-07-26 12:39:37,062] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'task1', 'manual__2022-07-26T12:39:30.437728+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpb5ty6nmt', '--error-file', '/tmp/tmpykq96m8l']
[2022-07-26 12:39:37,089] {standard_task_runner.py:80} INFO - Job 118: Subtask task1
[2022-07-26 12:39:37,485] {task_command.py:371} INFO - Running <TaskInstance: our_first_dag.task1 manual__2022-07-26T12:39:30.437728+00:00 [running]> on host 24820bb59fd1
[2022-07-26 12:39:37,861] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=our_first_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T12:39:30.437728+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T12:39:30.437728+00:00
[2022-07-26 12:39:37,868] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-26 12:39:37,889] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'Hello word, first task']
[2022-07-26 12:39:37,932] {subprocess.py:85} INFO - Output:
[2022-07-26 12:39:37,997] {subprocess.py:92} INFO - bash: line 1: Hello: command not found
[2022-07-26 12:39:38,004] {subprocess.py:96} INFO - Command exited with return code 127
[2022-07-26 12:39:38,068] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-07-26 12:39:38,094] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag, task_id=task1, execution_date=20220726T123930, start_date=20220726T123934, end_date=20220726T123938
[2022-07-26 12:39:38,155] {standard_task_runner.py:97} ERROR - Failed to execute job 118 for task task1 (Bash command failed. The command returned a non-zero exit code 127.; 4179)
[2022-07-26 12:39:38,261] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 12:39:38,669] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
